# Generated by Django 3.0.3 on 2020-04-24 13:32

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media/avatars', validators=[utils.validators.validate_document_extension, utils.validators.validate_document_size]),
        ),
    ]
