# Generated by Django 3.0.3 on 2020-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'CLINIC_IS_PRIVATE'), (2, 'CLINIC_IS_STATE')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'THERAPEUTIC_DEPARTMENT'), (2, 'SURGERY_DEPARTMENT'), (3, 'TRAUMA_DEPARTMENT'), (4, 'NEUROSURGICAL_DEPARTMENT'), (5, 'CARDIAC_DEPARTMENT'), (6, 'INTENSIVE_CARE_DEPARTMENT')], default=1)),
                ('info', models.TextField()),
                ('floor', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('experience', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'By card'), (2, 'By cash')], default=2)),
                ('date', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'ROENTGEN_SERVICE'), (2, 'ULTRASOUND_SERVICE'), (3, 'FLUOROGRAPHY_SERVICE'), (4, 'NOTE_86'), (5, 'NOTE_94')])),
                ('price', models.FloatField()),
                ('cabinet', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
