# Generated by Django 3.0.5 on 2020-04-24 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'CLINIC_IS_PRIVATE'), (2, 'CLINIC_IS_STATE')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'THERAPEUTIC_DEPARTMENT'), (2, 'SURGERY_DEPARTMENT'), (3, 'TRAUMA_DEPARTMENT'), (4, 'NEUROSURGICAL_DEPARTMENT'), (5, 'CARDIAC_DEPARTMENT'), (6, 'INTENSIVE_CARE_DEPARTMENT')], default=1)),
                ('info', models.TextField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.Clinic')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('cabinet', models.PositiveSmallIntegerField()),
                ('salary', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.Clinic')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.Department')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'ROENTGEN_SERVICE'), (2, 'ULTRASOUND_SERVICE'), (3, 'FLUOROGRAPHY_SERVICE'), (4, 'NOTE_86'), (5, 'NOTE_94')])),
                ('price', models.FloatField()),
                ('cabinet', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'By card'), (2, 'By cash')], default=2)),
                ('date', models.CharField(max_length=10000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_orders', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_doctors', to='core.Doctor')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_services', to='core.Service')),
            ],
        ),
    ]
