CLINIC_PRIVATE = 1
CLINIC_STATE = 2

CLINIC_STATUSES = (
    (CLINIC_PRIVATE,'CLINIC_IS_PRIVATE'),
    (CLINIC_STATE,'CLINIC_IS_STATE')
)

THERAPEUTIC_DEPARTMENT = 1
SURGERY_DEPARTMENT = 2
TRAUMA_DEPARTMENT = 3
NEUROSURGICAL_DEPARTMENT = 4
CARDIAC_DEPARTMENT = 5
INTENSIVE_CARE_DEPARTMENT = 6

CLINIC_DEPARTMENTS = (
    (THERAPEUTIC_DEPARTMENT,'THERAPEUTIC_DEPARTMENT'),
    (SURGERY_DEPARTMENT, 'SURGERY_DEPARTMENT'),
    (TRAUMA_DEPARTMENT, 'TRAUMA_DEPARTMENT'),
    (NEUROSURGICAL_DEPARTMENT, 'NEUROSURGICAL_DEPARTMENT'),
    (CARDIAC_DEPARTMENT, 'CARDIAC_DEPARTMENT'),
    (INTENSIVE_CARE_DEPARTMENT, 'INTENSIVE_CARE_DEPARTMENT')

)

ROENTGEN_SERVICE = 1
ULTRASOUND_SERVICE = 2
FLUOROGRAPHY_SERVICE = 3
NOTE_86 = 4
NOTE_94 = 5

CLINIC_SERVICES = (
    (ROENTGEN_SERVICE, 'ROENTGEN_SERVICE'),
    (ULTRASOUND_SERVICE, 'ULTRASOUND_SERVICE'),
    (FLUOROGRAPHY_SERVICE, 'FLUOROGRAPHY_SERVICE'),
    (NOTE_86, 'NOTE_86'),
    (NOTE_94, 'NOTE_94')
)

PAYMENT_VIA_CARD = 1
PAYMENT_VIA_CASH = 2

PAYMENT_TYPES = (
    (PAYMENT_VIA_CARD, 'By card'),
    (PAYMENT_VIA_CASH, 'By cash')
)