DISEASE_ACUTE = 1
DISEASE_CHRONIC = 2
DISEASE_CLINICAL = 3
DISEASE_SURVEY = 0

DISEASE_TYPES = (
    (DISEASE_ACUTE, 'ACUTE'),
    (DISEASE_CHRONIC, 'CHRONIC'),
    (DISEASE_CLINICAL, 'CLINICAL'),
    (DISEASE_SURVEY, 'SURVEY')
)
